<a href="https://colab.research.google.com/github/Oodysseass/pattern-recognition/blob/romanos/SVM_for_partD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#First we will try SVM because:
#    Effective for high-dimensional spaces.
#    Works well for both linear and non-linear data.
#    Can be memory-intensive for large datasets.(our 5000 samples are not that large)
#    We also have it from part C

In [6]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

#Loading data
data = np.loadtxt("datasetC.csv", delimiter=",", dtype=np.float64)
print (data)


#Last column containing Labels
features = data[:,0:-1]
labels = data[:, -1]

#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

#Scaling the features
#scaler = StandardScaler()
#X_train_scaled = scaler.fit_transform(X_train)
#X_test_scaled = scaler.fit_transform(X_test)
#print (X_train_scaled)

#Initialize the SVM
classifier = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)

# Train the SVM model
classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = classifier.predict(X_test)

# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print('\nConfusion Matrix:')
print(conf_matrix)
print('\nClassification Report:')
print(classification_rep)



[[ 0.13155   0.84036  -1.1277   ... -0.76285   0.33389   5.      ]
 [-0.2425    0.51161  -1.0429   ...  0.42895  -0.83821   4.      ]
 [ 0.22558   0.25723   1.5195   ... -0.88156   0.75886   1.      ]
 ...
 [ 2.0313    0.13828   1.4753   ... -0.21938   0.4007    2.      ]
 [-0.47172  -0.45778   0.86395  ...  0.11341   1.7662    3.      ]
 [ 0.74697   0.025161  1.3557   ...  0.21997   0.42807   4.      ]]
Accuracy: 0.85

Confusion Matrix:
[[205   2   0   1   7]
 [ 16 169  10  11   4]
 [  4   6 180   9  15]
 [ 11   9   2 182   6]
 [  3   2  22   8 116]]

Classification Report:
              precision    recall  f1-score   support

         1.0       0.86      0.95      0.90       215
         2.0       0.90      0.80      0.85       210
         3.0       0.84      0.84      0.84       214
         4.0       0.86      0.87      0.86       210
         5.0       0.78      0.77      0.78       151

    accuracy                           0.85      1000
   macro avg       0.85      0.85     